version: "3"

services:
  cache:
    image: "redis:alpine"
    container_name: mission_ama_cache
    ports:
      - "127.0.0.1:6379:6379"
  db:
    image: postgres:alpine
    container_name: mission_ama_db
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=mission_ama
