// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/zizouhuweidi/mission-ama/ent/employee"
	"github.com/zizouhuweidi/mission-ama/ent/mission"
	"github.com/zizouhuweidi/mission-ama/ent/predicate"
)

// EmployeeUpdate is the builder for updating Employee entities.
type EmployeeUpdate struct {
	config
	hooks    []Hook
	mutation *EmployeeMutation
}

// Where appends a list predicates to the EmployeeUpdate builder.
func (eu *EmployeeUpdate) Where(ps ...predicate.Employee) *EmployeeUpdate {
	eu.mutation.Where(ps...)
	return eu
}

// SetName sets the "name" field.
func (eu *EmployeeUpdate) SetName(s string) *EmployeeUpdate {
	eu.mutation.SetName(s)
	return eu
}

// SetPhone sets the "phone" field.
func (eu *EmployeeUpdate) SetPhone(i int) *EmployeeUpdate {
	eu.mutation.ResetPhone()
	eu.mutation.SetPhone(i)
	return eu
}

// AddPhone adds i to the "phone" field.
func (eu *EmployeeUpdate) AddPhone(i int) *EmployeeUpdate {
	eu.mutation.AddPhone(i)
	return eu
}

// SetCSP sets the "CSP" field.
func (eu *EmployeeUpdate) SetCSP(b bool) *EmployeeUpdate {
	eu.mutation.SetCSP(b)
	return eu
}

// SetNillableCSP sets the "CSP" field if the given value is not nil.
func (eu *EmployeeUpdate) SetNillableCSP(b *bool) *EmployeeUpdate {
	if b != nil {
		eu.SetCSP(*b)
	}
	return eu
}

// SetOccupation sets the "occupation" field.
func (eu *EmployeeUpdate) SetOccupation(s string) *EmployeeUpdate {
	eu.mutation.SetOccupation(s)
	return eu
}

// SetNillableOccupation sets the "occupation" field if the given value is not nil.
func (eu *EmployeeUpdate) SetNillableOccupation(s *string) *EmployeeUpdate {
	if s != nil {
		eu.SetOccupation(*s)
	}
	return eu
}

// ClearOccupation clears the value of the "occupation" field.
func (eu *EmployeeUpdate) ClearOccupation() *EmployeeUpdate {
	eu.mutation.ClearOccupation()
	return eu
}

// AddMissionIDs adds the "mission" edge to the Mission entity by IDs.
func (eu *EmployeeUpdate) AddMissionIDs(ids ...int) *EmployeeUpdate {
	eu.mutation.AddMissionIDs(ids...)
	return eu
}

// AddMission adds the "mission" edges to the Mission entity.
func (eu *EmployeeUpdate) AddMission(m ...*Mission) *EmployeeUpdate {
	ids := make([]int, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return eu.AddMissionIDs(ids...)
}

// Mutation returns the EmployeeMutation object of the builder.
func (eu *EmployeeUpdate) Mutation() *EmployeeMutation {
	return eu.mutation
}

// ClearMission clears all "mission" edges to the Mission entity.
func (eu *EmployeeUpdate) ClearMission() *EmployeeUpdate {
	eu.mutation.ClearMission()
	return eu
}

// RemoveMissionIDs removes the "mission" edge to Mission entities by IDs.
func (eu *EmployeeUpdate) RemoveMissionIDs(ids ...int) *EmployeeUpdate {
	eu.mutation.RemoveMissionIDs(ids...)
	return eu
}

// RemoveMission removes "mission" edges to Mission entities.
func (eu *EmployeeUpdate) RemoveMission(m ...*Mission) *EmployeeUpdate {
	ids := make([]int, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return eu.RemoveMissionIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (eu *EmployeeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, eu.sqlSave, eu.mutation, eu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (eu *EmployeeUpdate) SaveX(ctx context.Context) int {
	affected, err := eu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (eu *EmployeeUpdate) Exec(ctx context.Context) error {
	_, err := eu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (eu *EmployeeUpdate) ExecX(ctx context.Context) {
	if err := eu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (eu *EmployeeUpdate) check() error {
	if v, ok := eu.mutation.Name(); ok {
		if err := employee.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Employee.name": %w`, err)}
		}
	}
	if v, ok := eu.mutation.Occupation(); ok {
		if err := employee.OccupationValidator(v); err != nil {
			return &ValidationError{Name: "occupation", err: fmt.Errorf(`ent: validator failed for field "Employee.occupation": %w`, err)}
		}
	}
	return nil
}

func (eu *EmployeeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := eu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(employee.Table, employee.Columns, sqlgraph.NewFieldSpec(employee.FieldID, field.TypeInt))
	if ps := eu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := eu.mutation.Name(); ok {
		_spec.SetField(employee.FieldName, field.TypeString, value)
	}
	if value, ok := eu.mutation.Phone(); ok {
		_spec.SetField(employee.FieldPhone, field.TypeInt, value)
	}
	if value, ok := eu.mutation.AddedPhone(); ok {
		_spec.AddField(employee.FieldPhone, field.TypeInt, value)
	}
	if value, ok := eu.mutation.CSP(); ok {
		_spec.SetField(employee.FieldCSP, field.TypeBool, value)
	}
	if value, ok := eu.mutation.Occupation(); ok {
		_spec.SetField(employee.FieldOccupation, field.TypeString, value)
	}
	if eu.mutation.OccupationCleared() {
		_spec.ClearField(employee.FieldOccupation, field.TypeString)
	}
	if eu.mutation.MissionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   employee.MissionTable,
			Columns: []string{employee.MissionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mission.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := eu.mutation.RemovedMissionIDs(); len(nodes) > 0 && !eu.mutation.MissionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   employee.MissionTable,
			Columns: []string{employee.MissionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mission.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := eu.mutation.MissionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   employee.MissionTable,
			Columns: []string{employee.MissionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mission.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, eu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{employee.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	eu.mutation.done = true
	return n, nil
}

// EmployeeUpdateOne is the builder for updating a single Employee entity.
type EmployeeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EmployeeMutation
}

// SetName sets the "name" field.
func (euo *EmployeeUpdateOne) SetName(s string) *EmployeeUpdateOne {
	euo.mutation.SetName(s)
	return euo
}

// SetPhone sets the "phone" field.
func (euo *EmployeeUpdateOne) SetPhone(i int) *EmployeeUpdateOne {
	euo.mutation.ResetPhone()
	euo.mutation.SetPhone(i)
	return euo
}

// AddPhone adds i to the "phone" field.
func (euo *EmployeeUpdateOne) AddPhone(i int) *EmployeeUpdateOne {
	euo.mutation.AddPhone(i)
	return euo
}

// SetCSP sets the "CSP" field.
func (euo *EmployeeUpdateOne) SetCSP(b bool) *EmployeeUpdateOne {
	euo.mutation.SetCSP(b)
	return euo
}

// SetNillableCSP sets the "CSP" field if the given value is not nil.
func (euo *EmployeeUpdateOne) SetNillableCSP(b *bool) *EmployeeUpdateOne {
	if b != nil {
		euo.SetCSP(*b)
	}
	return euo
}

// SetOccupation sets the "occupation" field.
func (euo *EmployeeUpdateOne) SetOccupation(s string) *EmployeeUpdateOne {
	euo.mutation.SetOccupation(s)
	return euo
}

// SetNillableOccupation sets the "occupation" field if the given value is not nil.
func (euo *EmployeeUpdateOne) SetNillableOccupation(s *string) *EmployeeUpdateOne {
	if s != nil {
		euo.SetOccupation(*s)
	}
	return euo
}

// ClearOccupation clears the value of the "occupation" field.
func (euo *EmployeeUpdateOne) ClearOccupation() *EmployeeUpdateOne {
	euo.mutation.ClearOccupation()
	return euo
}

// AddMissionIDs adds the "mission" edge to the Mission entity by IDs.
func (euo *EmployeeUpdateOne) AddMissionIDs(ids ...int) *EmployeeUpdateOne {
	euo.mutation.AddMissionIDs(ids...)
	return euo
}

// AddMission adds the "mission" edges to the Mission entity.
func (euo *EmployeeUpdateOne) AddMission(m ...*Mission) *EmployeeUpdateOne {
	ids := make([]int, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return euo.AddMissionIDs(ids...)
}

// Mutation returns the EmployeeMutation object of the builder.
func (euo *EmployeeUpdateOne) Mutation() *EmployeeMutation {
	return euo.mutation
}

// ClearMission clears all "mission" edges to the Mission entity.
func (euo *EmployeeUpdateOne) ClearMission() *EmployeeUpdateOne {
	euo.mutation.ClearMission()
	return euo
}

// RemoveMissionIDs removes the "mission" edge to Mission entities by IDs.
func (euo *EmployeeUpdateOne) RemoveMissionIDs(ids ...int) *EmployeeUpdateOne {
	euo.mutation.RemoveMissionIDs(ids...)
	return euo
}

// RemoveMission removes "mission" edges to Mission entities.
func (euo *EmployeeUpdateOne) RemoveMission(m ...*Mission) *EmployeeUpdateOne {
	ids := make([]int, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return euo.RemoveMissionIDs(ids...)
}

// Where appends a list predicates to the EmployeeUpdate builder.
func (euo *EmployeeUpdateOne) Where(ps ...predicate.Employee) *EmployeeUpdateOne {
	euo.mutation.Where(ps...)
	return euo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (euo *EmployeeUpdateOne) Select(field string, fields ...string) *EmployeeUpdateOne {
	euo.fields = append([]string{field}, fields...)
	return euo
}

// Save executes the query and returns the updated Employee entity.
func (euo *EmployeeUpdateOne) Save(ctx context.Context) (*Employee, error) {
	return withHooks(ctx, euo.sqlSave, euo.mutation, euo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (euo *EmployeeUpdateOne) SaveX(ctx context.Context) *Employee {
	node, err := euo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (euo *EmployeeUpdateOne) Exec(ctx context.Context) error {
	_, err := euo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (euo *EmployeeUpdateOne) ExecX(ctx context.Context) {
	if err := euo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (euo *EmployeeUpdateOne) check() error {
	if v, ok := euo.mutation.Name(); ok {
		if err := employee.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Employee.name": %w`, err)}
		}
	}
	if v, ok := euo.mutation.Occupation(); ok {
		if err := employee.OccupationValidator(v); err != nil {
			return &ValidationError{Name: "occupation", err: fmt.Errorf(`ent: validator failed for field "Employee.occupation": %w`, err)}
		}
	}
	return nil
}

func (euo *EmployeeUpdateOne) sqlSave(ctx context.Context) (_node *Employee, err error) {
	if err := euo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(employee.Table, employee.Columns, sqlgraph.NewFieldSpec(employee.FieldID, field.TypeInt))
	id, ok := euo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Employee.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := euo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, employee.FieldID)
		for _, f := range fields {
			if !employee.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != employee.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := euo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := euo.mutation.Name(); ok {
		_spec.SetField(employee.FieldName, field.TypeString, value)
	}
	if value, ok := euo.mutation.Phone(); ok {
		_spec.SetField(employee.FieldPhone, field.TypeInt, value)
	}
	if value, ok := euo.mutation.AddedPhone(); ok {
		_spec.AddField(employee.FieldPhone, field.TypeInt, value)
	}
	if value, ok := euo.mutation.CSP(); ok {
		_spec.SetField(employee.FieldCSP, field.TypeBool, value)
	}
	if value, ok := euo.mutation.Occupation(); ok {
		_spec.SetField(employee.FieldOccupation, field.TypeString, value)
	}
	if euo.mutation.OccupationCleared() {
		_spec.ClearField(employee.FieldOccupation, field.TypeString)
	}
	if euo.mutation.MissionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   employee.MissionTable,
			Columns: []string{employee.MissionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mission.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := euo.mutation.RemovedMissionIDs(); len(nodes) > 0 && !euo.mutation.MissionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   employee.MissionTable,
			Columns: []string{employee.MissionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mission.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := euo.mutation.MissionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   employee.MissionTable,
			Columns: []string{employee.MissionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mission.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Employee{config: euo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, euo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{employee.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	euo.mutation.done = true
	return _node, nil
}
